// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoreRunning():Promise<boolean>;

export function CoreStatus():Promise<Record<string, any>>;

export function EnvDetect():Promise<Record<string, any>>;

export function OpenLogDir():Promise<string>;

export function PollLogs():Promise<Array<string>>;

export function StartCore(arg1:string):Promise<string>;

export function StopCore():Promise<string>;

export function TailLog():Promise<Array<string>>;

export function Version():Promise<string>;
