// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoreRunning() {
  return window['go']['main']['App']['CoreRunning']();
}

export function CoreStatus() {
  return window['go']['main']['App']['CoreStatus']();
}

export function EnvDetect() {
  return window['go']['main']['App']['EnvDetect']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PollLogs() {
  return window['go']['main']['App']['PollLogs']();
}

export function StartCore(arg1) {
  return window['go']['main']['App']['StartCore'](arg1);
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function TailLog() {
  return window['go']['main']['App']['TailLog']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
