# -*- coding: utf-8 -*-
"""从 Location.xml + map_locations.js 生成 app/js/regions.js（4 级地名，简体中文全量）
r1=8 大区（show=1）| r2=24 地形区（show=2）| r3=363 细地名（show=4，全量简体中文名）
坐标换算：px = (游戏坐标 X/Z)*2 + 偏移(12000/10000)
中文名来源：官方简体（游戏内/攻略站核对）+ 日文罗马音按官方译名惯例音译
"""
import re, json

xml = open(r'E:\WorkSpace\BOTWmap\waypoint-data\Location.xml', encoding='utf-8').read()
items = re.findall(r'<value ShowLevel="(\d+)">\s*<MessageID type="string">([^<]+)</MessageID>\s*<Translate X="([^"]+)" Y="[^"]+" Z="([^"]+)" />\s*<Type>(\d+)</Type>', xml)
by_id = {}
for show, mid, x, z, typ in items:
    mid = mid.strip()
    if mid not in by_id or int(show) < by_id[mid][0]:
        by_id[mid] = (int(show), float(x.rstrip('f')), float(z.rstrip('f')))

# 回退源：map_locations.js（村庄/桥/设施类地点，x=游戏X, y=游戏Z）
mljs = open(r'E:\WorkSpace\BOTWmap\waypoint-data\map_locations.js', encoding='utf-8').read()
for m in re.finditer(r'\{"internal_name":"([^"]+)", "display_name":"([^"]+)", "x":([-\d.]+), "y":([-\d.]+)\}', mljs):
    iid = m.group(1).replace('Location_', '')
    if iid not in by_id:
        by_id[iid] = (99, float(m.group(3)), float(m.group(4)))

def to_px(x, z):
    return [round(2 * x + 12000), round(2 * z + 10000)]

def add(out, key, cn, lv):
    if key not in by_id:
        print('!! 缺 ID:', key, cn)
        return
    s, x, z = by_id[key]
    out.append({'n': cn, 'px': to_px(x, z), 'lv': lv})

out = []
# ---- r1 大区（8）----
R1 = [
    ("MapRegion_Hebura", "海布拉地区"),
    ("MapRegion_Eldin", "奥尔汀地区"),
    ("MapRegion_Tamul", "阿卡莱地区"),
    ("MapRegion_Lanayru", "拉聂尔地区"),
    ("MapRegion_Hateru", "哈特诺地区"),
    ("MapRegion_HyrulePrairie", "中央海拉鲁"),
    ("MapRegion_Firone", "费罗尼地区"),
    ("MapRegion_Gerudo", "格鲁德地区"),
]
# ---- r2 地形区（24，show=2 全量）----
R2 = [
    ("MapArea_DeathMountain", "死亡之山"),
    ("MapArea_EastHateru", "东哈特诺"),
    ("MapArea_EldinCanyon", "奥尔汀大峡谷"),
    ("MapArea_EldinMountains", "奥尔汀山脉"),
    ("MapArea_FironeGrassland", "费罗尼草原"),
    ("MapArea_FironeSea", "费罗尼海"),
    ("MapArea_GerudoDesert", "格鲁德沙漠"),
    ("MapArea_GerudoHighlands", "格鲁德高地"),
    ("MapArea_HateruSea", "哈特诺海"),
    ("MapArea_HeburaMountains", "海布拉山脉"),
    ("MapArea_HyliaLake", "海利亚湖"),
    ("MapArea_HyruleForest", "海拉鲁大森林"),
    ("MapArea_HyruleHill", "海拉鲁丘陵"),
    ("MapArea_LanayruSea", "拉聂尔海"),
    ("MapArea_LanayruWaterSources", "拉聂尔大水源"),
    ("MapArea_LanayruWetlands", "拉聂尔湿地"),
    ("MapArea_LiveMountain", "拉聂尔山"),
    ("MapArea_TabantaFrontier", "塔邦达边境"),
    ("TabantaSnow", "塔邦达冻原"),
    ("MapArea_TamulOutback", "深远阿卡莱"),
    ("MapArea_TamulPlateau", "阿卡莱高原"),
    ("MapArea_TamulSea", "阿卡莱海"),
    ("MapArea_WestHateru", "西哈特诺"),
    ("MapArea_CentralHyrule", "海拉鲁平原"),
]
# ---- r3 细地名（363，show=4 全量；中文名=官方简体或按官方译名惯例音译）----
R3 = [
    ("AagetoMt", "阿格托山"),
    ("AdeyaLake", "阿德雅湖"),
    ("AgePlateau", "阿格台地"),
    ("AgunaiLake", "阿古奈湖"),
    ("AkazaMt", "阿卡扎山"),
    ("AmimePlateau", "阿米梅台地"),
    ("AmonenePlateau", "阿莫内内台地"),
    ("AnbonBeach", "安邦海滩"),
    ("AnchoBeach", "安乔海滩"),
    ("AnoleLake", "阿诺尔湖"),
    ("AnoleTunnel", "阿诺尔隧道"),
    ("ArafuraPlain", "阿拉弗拉平原"),
    ("AraisoBeach", "阿莱索海滩"),
    ("AzimetosPlateau", "阿吉梅托斯台地"),
    ("BachimakuMt", "巴奇马库山"),
    ("BaconCliff", "培根断崖"),
    ("BameHill", "巴美山丘"),
    ("BanmezaLake", "班梅扎湖"),
    ("BantaValley", "终焉之谷"),
    ("BarakkiPlain", "巴拉基平原"),
    ("BarumePlain", "巴鲁梅平原"),
    ("BigalLake", "比加尔湖"),
    ("BiginaTrees", "比吉纳树林"),
    ("BiridinHill", "比利丁山丘"),
    ("BironSnow", "比隆雪原"),
    ("BituoValley", "比楚奥谷"),
    ("BlindForest", "盲目森林"),
    ("BlizzarValley", "暴雪谷"),
    ("BokoboLake", "博科博湖"),
    ("BonrasForest", "邦拉斯森林"),
    ("BoraraCape", "博拉拉岬"),
    ("BottuBay", "博图湾"),
    ("BrostarPlain", "布罗斯塔平原"),
    ("BuhaIslands", "布哈群岛"),
    ("BuibuiTrees", "布伊布伊树林"),
    ("BuichadaPlateau", "布伊查达台地"),
    ("BuidaLake", "布伊达湖"),
    ("BumiPlain", "布米平原"),
    ("BuramuPlateau", "布拉姆台地"),
    ("ChagaraMt", "查加拉山"),
    ("ChuonoPond", "丘奥诺池塘"),
    ("CresiaPeninsula", "克雷西亚半岛"),
    ("DamzelForest", "达姆泽尔森林"),
    ("DanioPlain", "达尼奥平原"),
    ("DarinoPond", "达里诺池塘"),
    ("DasukidaMt", "达斯基达山"),
    ("DasukidaPlateau", "达斯基达台地"),
    ("DatsuPlain", "达楚平原"),
    ("DeathCaldera", "死亡破火山口"),
    ("DekamuPlain", "德卡姆平原"),
    ("DokamamaPlain", "多卡玛玛平原"),
    ("DokuroPond", "骷髅池"),
    ("DonLake", "顿湖"),
    ("DotiBeach", "多蒂海滩"),
    ("DragonsFar", "龙之遥地"),
    ("EagleBridge", "鹰桥"),
    ("EastEunpoHighlands", "东云波高地"),
    ("EastGerudo", "东格鲁德"),
    ("EastGerudoPlateau", "东格鲁德台地"),
    ("EastShrine", "东祠"),
    ("ElegLake", "埃雷格湖"),
    ("EnRiver", "恩河"),
    ("EquePlateau", "埃库埃台地"),
    ("ErumedaPlateau", "埃鲁梅达台地"),
    ("EunpoHighlands", "云波高地"),
    ("ExpaTrees", "埃克斯帕树林"),
    ("FairyForest", "妖精之森"),
    ("FenaMt", "费纳山"),
    ("FeoreRiver", "费奥雷河"),
    ("FinrasForest", "芬拉斯森林"),
    ("FlogPond", "弗罗格池塘"),
    ("FloriaFalls", "花柔莉亚大瀑布"),
    ("FloriaRiver", "花柔莉亚河"),
    ("FuruboLake", "弗鲁博湖"),
    ("GakanakkyoPlain", "西海拉鲁平原"),
    ("GamettaPlateau", "加梅塔台地"),
    ("GaneLake", "加内湖"),
    ("GarakishiPass", "加拉基希隘口"),
    ("GasemaDam", "茹特拉大坝"),
    ("GasemaRiver", "茹特拉河"),
    ("GashamaHill", "加沙玛山丘"),
    ("GashamahiMt", "加沙玛希山"),
    ("GatakaraPond", "加塔卡拉池塘"),
    ("GatinLake", "加廷湖"),
    ("GenLake", "根湖"),
    ("GeraRiver", "格拉河"),
    ("GerudoCanyon", "格鲁德峡谷"),
    ("GerudoSummit", "格鲁德山顶"),
    ("GiankonIsland", "吉安孔岛"),
    ("GibogaHill", "吉博加山丘"),
    ("GibururuMt", "露朵山"),
    ("GigiLake", "吉吉湖"),
    ("GiminoPond", "吉米诺池塘"),
    ("GimpoMt", "金波山"),
    ("GisaHill", "吉萨山丘"),
    ("GishiHill", "吉希山丘"),
    ("GobyMt", "戈比山"),
    ("GoinaPlateau", "戈伊纳台地"),
    ("GoronSpa", "鼓隆温泉"),
    ("GoyoLake", "戈约湖"),
    ("GumaroValley", "古马罗谷"),
    ("GutinizaPlain", "古蒂尼扎平原"),
    ("GyunaIsland", "久纳岛"),
    ("HagoromoLake", "羽衣湖"),
    ("HamiyonPlain", "哈米永平原"),
    ("HarayaLake", "哈拉亚湖"),
    ("HashibiroLake", "哈希毕罗湖"),
    ("HatenoBay", "哈特诺湾"),
    ("HatenoBeach", "哈特诺海滩"),
    ("HatenokoIsland", "哈特诺科岛"),
    ("HawkMt", "霍克山"),
    ("HeburaEastSummit", "海布拉山东岳"),
    ("HeburaIcicle", "海布拉冰柱"),
    ("HeburaMt_North", "海布拉北峰"),
    ("HeburaNorthSummit", "海布拉山北岳"),
    ("HeburaPeak", "海布拉山山顶"),
    ("HeburaSouthSummit", "海布拉山南岳"),
    ("HeburaTundera", "海布拉冻原"),
    ("HeburaWestSummit", "海布拉山西岳"),
    ("HemaHill", "赫马山丘"),
    ("HesonaiValley", "赫索奈谷"),
    ("HigakkareBeach", "北阿卡莱海滩"),
    ("HigakkarePlain", "东阿卡莱平原"),
    ("HigashinoBay", "东野湾"),
    ("HimeidaMt", "姬伊达山"),
    ("HopeBridge", "希望桥"),
    ("HyliaMt", "海利亚山"),
    ("HyliaRiver", "海利亚河"),
    ("HyralIslands", "海利亚岛"),
    ("Hyrule_Out", "海拉鲁郊外"),
    ("IbaraPlateau", "伊巴拉台地"),
    ("IkokoPlateau", "伊科科台地"),
    ("ImeruMt", "伊梅鲁山"),
    ("IooValley", "伊奥奥谷"),
    ("IrimoLake", "伊里莫湖"),
    ("IrimoRiver", "伊里莫河"),
    ("IsakiCape", "伊萨基岬"),
    ("IsakuIslands", "伊萨库群岛"),
    ("JedaPlateau", "杰达台地"),
    ("JijigegeMt", "吉吉格格山"),
    ("JiuRiver", "卓拉河"),
    ("KagossaMt", "卡戈萨山"),
    ("KaiyanPlain", "凯扬平原"),
    ("KakamoLake", "卡卡莫湖"),
    ("KakaomePlain", "卡卡奥梅平原"),
    ("KakufusaPlain", "卡库夫萨平原"),
    ("KamasuPlateau", "卡马斯台地"),
    ("KamutariPlateau", "卡姆塔里台地"),
    ("KapporeMt", "卡波雷山"),
    ("KarimikiLake", "卡里米基湖"),
    ("KarusaValley", "卡鲁萨谷"),
    ("KasuraMt", "卡斯拉山"),
    ("KattoriPlateau", "卡托里台地"),
    ("KaturaRiver", "卡楚拉河"),
    ("KauLake", "卡乌湖"),
    ("KazanaDungeon", "卡扎纳洞窟"),
    ("KazuryuLake", "卡兹留湖"),
    ("KazuryuRiver", "卡兹留河"),
    ("KazusuPass", "卡兹苏斯隘口"),
    ("KibakkaSnow", "基巴卡雪原"),
    ("KibinaLake", "基比纳湖"),
    ("KihirePlain", "基希雷平原"),
    ("KikinosaMt", "基基诺萨山"),
    ("KikinosaPlain", "基基诺萨平原"),
    ("KimarikaMt", "基马里卡山"),
    ("KimarikaPlateau", "基马里卡台地"),
    ("KingValley", "金谷"),
    ("KinmePlateau", "金梅台地"),
    ("KinshoiMt", "金肖伊山"),
    ("KirisasaPlateau", "基里萨萨台地"),
    ("KiriyabuMt", "基里亚布山"),
    ("KitakkareBeach", "北阿卡莱海滩"),
    ("KitakkarePlain", "北阿卡莱平原"),
    ("KitakkarePlateau", "北阿卡莱台地"),
    ("KitanoBay", "北野湾"),
    ("KiyanbaTrees", "基扬巴树林"),
    ("KoganeyaLake", "黄金谷湖"),
    ("KokuppiSnow", "科库皮雪原"),
    ("KokuwaLake", "科库瓦湖"),
    ("KomoreBeach", "科莫雷海滩"),
    ("KondanaLake", "孔达纳湖"),
    ("KoshaIsland", "科沙岛"),
    ("KuhanLake", "库汉湖"),
    ("KukujaValley", "库库加谷"),
    ("KumPlateau", "库姆台地"),
    ("KunaiLake", "库奈湖"),
    ("KurindaPrairie", "库林达草原"),
    ("KurisobeSnow", "库里索贝雪原"),
    ("KuroidaPlateau", "库罗伊达台地"),
    ("KutenLake", "库滕湖"),
    ("KutiffMt", "库蒂夫山"),
    ("LakeFloria", "花柔莉亚湖"),
    ("LanayruBay", "拉聂尔湾"),
    ("LaveBeach", "拉维海滩"),
    ("MacusePeninsula", "马丘泽半岛"),
    ("MakuminoValley", "马库米诺谷"),
    ("ManbaLake", "曼巴湖"),
    ("MarittaHill", "马里塔山丘"),
    ("MarittaPrairie", "马里塔草原"),
    ("MasazuRock", "马萨祖岩"),
    ("MedakaValley", "梅达卡谷"),
    ("MeganeRock", "眼镜岩"),
    ("MemeMt", "梅梅山"),
    ("MenadaBeach", "梅纳达海滩"),
    ("MerkayaLowTrees", "梅尔卡亚矮树林"),
    ("MezusuPass", "梅祖苏斯隘口"),
    ("MiddleTrees", "中部树林"),
    ("MihekoBay", "米赫科湾"),
    ("MinakkareFalls", "南阿卡莱瀑布"),
    ("MinakkareLake", "南阿卡莱湖"),
    ("MinakkarePlain", "南阿卡莱平原"),
    ("MinaminoBay", "南野湾"),
    ("MizemakuMt", "米泽马库山"),
    ("MomoMt", "桃山"),
    ("MoriMt", "森山"),
    ("MoroLake", "米考湖"),
    ("MorudaMt", "莫鲁达山"),
    ("MorugaMt", "莫鲁加山"),
    ("MuguriPlain", "穆古里平原"),
    ("NaganizaHill", "纳加尼扎山丘"),
    ("NagyuPlateau", "纳久台地"),
    ("NaierunPeninsula", "奈鲁恩半岛"),
    ("NanaimoPlain", "纳奈莫平原"),
    ("NangoPond", "南戈池塘"),
    ("NaruguPeninsula", "纳鲁古半岛"),
    ("NefraHill", "内弗拉高地"),
    ("NezuppoTrees", "内祖波树林"),
    ("NiiLake", "尼伊湖"),
    ("NikakaIsland", "尼卡卡岛"),
    ("NishakkarePlain", "西阿卡莱平原"),
    ("NitariBeach", "尼塔里海滩"),
    ("NomyPlain", "诺米平原"),
    ("NorthHugeStone", "北部巨石"),
    ("NutsLake", "纳茨湖"),
    ("OkuAkkarePlain", "奥库阿卡莱平原"),
    ("OkuwaLake", "奥库瓦湖"),
    ("OngiForest", "翁吉森林"),
    ("OoosePlain", "大濑平原"),
    ("OrupaPlateau", "奥鲁帕台地"),
    ("OshoromaLake", "露朵湖"),
    ("OtsukoWet", "奥楚科湿地"),
    ("PafaBeach", "帕法海滩"),
    ("PaiyuBay", "派尤湾"),
    ("PakanchiIsland", "帕坎奇岛"),
    ("PaparaPlateau", "帕帕拉台地"),
    ("PearlWaste", "帕鲁荒地"),
    ("PeridoBarrier", "佩里多屏障"),
    ("PongagaMt", "蓬加加山"),
    ("PoponMt", "萨托利山"),
    ("PstaLake", "普斯塔湖"),
    ("PukiroroMt", "普基罗罗山"),
    ("PukuntoMt", "普昆托山"),
    ("PupukoreFalls", "普普科雷瀑布"),
    ("RaberaWet", "拉贝拉湿地"),
    ("RapikuruPlateau", "拉皮库鲁台地"),
    ("RapinyaPlateau", "拉平亚台地"),
    ("RaruLake", "拉鲁湖"),
    ("RashamaPlain", "拉沙玛平原"),
    ("RazezePlateau", "拉泽泽台地"),
    ("RiaroTrees", "里亚罗树林"),
    ("RiberaForest", "里贝拉森林"),
    ("RibuchaPlateau", "里布查台地"),
    ("Rikona_Peninshra", "里科纳半岛"),
    ("RinosPass", "里诺斯隘口"),
    ("RirimukuHighlands", "里里穆库高地"),
    ("RirimukuMt", "里里穆库山"),
    ("RiritotoLake", "里里托托湖"),
    ("RishakutoPlateau", "里沙库托台地"),
    ("RodaiLake", "罗代湖"),
    ("RogyLake", "罗吉湖"),
    ("RokomakuMt", "罗科马库山"),
    ("RonronFarm", "隆隆牧场"),
    ("RonronRiver", "隆隆河"),
    ("RoshiganLake", "罗希甘湖"),
    ("RosomaLake", "罗索马湖"),
    ("RuberaHill", "鲁贝拉山丘"),
    ("RutesLake", "鲁特斯湖"),
    ("RutimaHill", "鲁蒂马山丘"),
    ("RutsuPlain", "鲁楚平原"),
    ("SaiMt", "赛山"),
    ("SanaePlateau", "早苗台地"),
    ("SanrosaLake", "桑罗萨湖"),
    ("SaohPoint", "萨奥夫岬"),
    ("SaphiasPlateau", "萨菲亚斯台地"),
    ("SarjonForest", "萨鲁容森林"),
    ("SasamuroBeach", "笹室海滩"),
    ("ShariverMt", "沙里瓦山"),
    ("ShikuriIslands", "希库里群岛"),
    ("ShimukaPlateau", "希穆卡台地"),
    ("ShinikkyoForest", "希尼基奥森林"),
    ("ShinyarkiPlateau", "希尼亚鲁基台地"),
    ("ShitanoPond", "下之池"),
    ("SojijiHill", "索吉吉山丘"),
    ("SonoPrairie", "索诺草原"),
    ("SoridaPeninsula", "索里达半岛"),
    ("SouthGerudoRuins", "南格鲁德遗迹"),
    ("SugrantForest", "苏格兰特森林"),
    ("SusonoLake", "裾野湖"),
    ("SusonoPlain", "裾野平原"),
    ("SusonoPond", "裾野池塘"),
    ("SusonoRiver", "裾野河"),
    ("SwanLake", "天鹅湖"),
    ("TabantaHill", "塔邦达山丘"),
    ("TabantaSnow_North", "北塔邦达雪原"),
    ("TabantaSnow_South", "南塔邦达雪原"),
    ("TafeaHill", "塔费亚山丘"),
    ("TagonaTrees", "塔戈纳树林"),
    ("TakkikaPlain", "塔基卡平原"),
    ("TamaLake", "玉湖"),
    ("TamulPlain", "塔穆尔平原"),
    ("TargarPlain", "塔鲁加尔平原"),
    ("TaruhoPlateau", "塔鲁霍台地"),
    ("TatsubaLake", "达楚巴湖"),
    ("TeguriPlain", "特古里平原"),
    ("TehotaWet", "特霍塔湿地"),
    ("TennoMt", "天诺山"),
    ("TeraPlain", "特拉平原"),
    ("TerumeMt", "特鲁梅山"),
    ("TerumePass", "特鲁梅隘口"),
    ("TohikiLake", "托希基湖"),
    ("TomiyoPlateau", "托米约台地"),
    ("TompoPlain", "罗玛尼平原"),
    ("TorumaDesert", "托鲁马沙漠"),
    ("TotenLake", "托滕湖"),
    ("TrakaIsland", "特拉卡岛"),
    ("TrakaIsland_Big", "特拉卡大岛"),
    ("TrakaIsland_Center", "特拉卡中央岛"),
    ("TrakaIsland_East", "特拉卡东岛"),
    ("TrakaIsland_New", "特拉卡新岛"),
    ("TrakaIsland_North", "特拉卡北岛"),
    ("TrakaIsland_Small", "特拉卡小岛"),
    ("TrakaIsland_South", "特拉卡南岛"),
    ("TrakaIsland_West", "特拉卡西岛"),
    ("TryCape", "特莱岬"),
    ("TsukaiePlateau", "楚卡伊埃台地"),
    ("TuaboSnow", "图阿博雪原"),
    ("TunbriPlain", "图恩布里平原"),
    ("TurasuLake", "图拉斯湖"),
    ("TutukikiSnow", "楚楚基基雪原"),
    ("TwinsMountain", "双子山"),
    ("UbotsuPlateau", "乌博楚台地"),
    ("UchoPlateau", "乌乔台地"),
    ("UkkoPond", "乌科池塘"),
    ("UraitoLake", "乌莱托湖"),
    ("UrokoCape", "鳞岬"),
    ("VPlateau", "V字台地"),
    ("WabiLake", "瓦比湖"),
    ("WatakaPlateau", "瓦塔卡台地"),
    ("WestEunpoHighlands", "西云波高地"),
    ("WestGerudo", "西格鲁德"),
    ("WestGerudoRuins", "西格鲁德遗迹"),
    ("XehaPlateau", "克塞哈台地"),
    ("YamabiLake", "山比湖"),
    ("YamariRiver", "亚马里河"),
    ("YarimoRiver", "亚里莫河"),
    ("YashinoBeach", "椰野海滩"),
    ("YuaSnow", "尤阿雪原"),
    ("ZamaPlain", "扎马平原"),
    ("ZaridoLake", "扎里多湖"),
    ("ZaridoPlateau", "扎里多台地"),
    ("ZifForest", "吉夫森林"),
    ("ZitoGreens", "吉托草原"),
    ("ZoraBridge", "卓拉大桥"),
]

for k, cn in R1: add(out, k, cn, 'r1')
for k, cn in R2: add(out, k, cn, 'r2')
for k, cn in R3: add(out, k, cn, 'r3')

js = "/* 地形/区域名（简体中文官方译名；r1大区/r2地形区/r3细地名，坐标=游戏坐标转逻辑像素） */\n"
js += "const BOTW_REGIONS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
open(r'E:\WorkSpace\BOTWmap\app\js\regions.js', 'w', encoding='utf-8').write(js)
print('生成 regions.js 共', len(out), '个')
from collections import Counter
print(Counter(r['lv'] for r in out))
missing = [k for k, cn in R1 + R2 + R3 if k not in by_id]
print('缺失 ID:', missing if missing else '无')
